# Generated by Django 3.2.8 on 2022-08-29 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('link_to_repository', models.URLField(blank=True, help_text='Project url', null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('date_create', models.DateField(editable=False)),
                ('date_update', models.DateField(editable=False)),
                ('is_active', models.BooleanField(default=False)),
                ('projects', models.ManyToManyField(to='taskapp.Project')),
            ],
        ),
    ]
